#!/usr/bin/env node
/**
 * Reads packages/cli/skills/ at build time and generates a TypeScript module
 * that exports every skill file as an in-memory data structure.
 * This lets compiled (bun --compile) and globally-installed binaries ship
 * bundled skills without relying on the filesystem at runtime.
 *
 * Usage: npx tsx scripts/embed-skills.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "fs"
import { join, relative, dirname } from "path"

const SCRIPT_DIR = dirname(new URL(import.meta.url).pathname)
const CLI_ROOT = join(SCRIPT_DIR, "..")
const SKILLS_DIR = join(CLI_ROOT, "skills")
const OUT_FILE = join(CLI_ROOT, "src", "generated", "embedded-skills.ts")

interface FileEntry {
  path: string
  content: string
}

function walk(dir: string, base: string): FileEntry[] {
  const entries: FileEntry[] = []
  for (const item of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, item.name)
    if (item.isDirectory()) {
      entries.push(...walk(fullPath, base))
    } else {
      entries.push({
        path: relative(base, fullPath),
        content: readFileSync(fullPath, "utf-8"),
      })
    }
  }
  return entries
}

function collectSkills(): Record<string, FileEntry[]> {
  const skills: Record<string, FileEntry[]> = {}
  for (const entry of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const skillDir = join(SKILLS_DIR, entry.name)
    const skillMd = join(skillDir, "SKILL.md")
    try {
      statSync(skillMd)
    } catch {
      continue
    }
    skills[entry.name] = walk(skillDir, skillDir)
  }
  return skills
}

function generate() {
  const skills = collectSkills()

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/embed-skills.ts — do not edit manually",
    "",
    "export interface EmbeddedFile {",
    "  path: string",
    "  content: string",
    "}",
    "",
    "export interface EmbeddedSkill {",
    "  name: string",
    "  files: EmbeddedFile[]",
    "}",
    "",
    "export const EMBEDDED_SKILLS: EmbeddedSkill[] = [",
  ]

  for (const [name, files] of Object.entries(skills).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  {`)
    lines.push(`    name: ${JSON.stringify(name)},`)
    lines.push(`    files: [`)
    for (const file of files.sort((a, b) => a.path.localeCompare(b.path))) {
      lines.push(`      {`)
      lines.push(`        path: ${JSON.stringify(file.path)},`)
      lines.push(`        content: ${JSON.stringify(file.content)},`)
      lines.push(`      },`)
    }
    lines.push(`    ],`)
    lines.push(`  },`)
  }

  lines.push("]")
  lines.push("")

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, lines.join("\n"), "utf-8")

  const totalFiles = Object.values(skills).reduce((sum, f) => sum + f.length, 0)
  console.log(
    `Embedded ${Object.keys(skills).length} skill(s) (${totalFiles} files) → ${relative(CLI_ROOT, OUT_FILE)}`
  )
}

generate()
